# Generated by Django 6.0.3 on 2026-04-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='recurrence_id',
            field=models.UUIDField(blank=True, help_text='Links recurring instances', null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='session_type',
            field=models.CharField(choices=[('study', 'Study Session'), ('class', 'Lesson/Class'), ('assignment', 'Assignment Focus'), ('exam', 'Exam/Test'), ('personal', 'Personal')], default='study', max_length=20),
        ),
    ]
