# Generated by Django 6.0.3 on 2026-04-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_chatmessage_diagram_code_chatmessage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
