# Generated by Django 6.0.3 on 2026-04-11 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_workspacemessage_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='workspace.workspacemessage'),
        ),
    ]
