# Generated by Django 6.0.3 on 2026-04-12 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_chat_history'),
        ('workspace', '0003_workspacemessage_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemessage',
            name='shared_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_shares', to='assignments.assignment'),
        ),
    ]
