# Generated by Django 5.2.14 on 2026-05-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_workspacemessage_audio_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='workspace_attachments/'),
        ),
        migrations.AddField(
            model_name='workspacemessage',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
