# Generated by Django 6.0.3 on 2026-04-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='chat_history',
            field=models.JSONField(default=list),
        ),
    ]
