/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicRouteImport } from './routes/topic'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as QuizzesRouteImport } from './routes/quizzes'
import { Route as PastPapersRouteImport } from './routes/past-papers'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SyllabusSubjectIdRouteImport } from './routes/syllabus.$subjectId'
import { Route as SubjectNotesSubjectRouteImport } from './routes/subject-notes.$subject'
import { Route as TopicNotesSubjectIdObjectiveIdRouteImport } from './routes/topic-notes.$subjectId.$objectiveId'
import { Route as PracticeSubjectIdObjectiveIdRouteImport } from './routes/practice.$subjectId.$objectiveId'

const TopicRoute = TopicRouteImport.update({
  id: '/topic',
  path: '/topic',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesRoute = QuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const PastPapersRoute = PastPapersRouteImport.update({
  id: '/past-papers',
  path: '/past-papers',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SyllabusSubjectIdRoute = SyllabusSubjectIdRouteImport.update({
  id: '/syllabus/$subjectId',
  path: '/syllabus/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectNotesSubjectRoute = SubjectNotesSubjectRouteImport.update({
  id: '/subject-notes/$subject',
  path: '/subject-notes/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicNotesSubjectIdObjectiveIdRoute =
  TopicNotesSubjectIdObjectiveIdRouteImport.update({
    id: '/topic-notes/$subjectId/$objectiveId',
    path: '/topic-notes/$subjectId/$objectiveId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeSubjectIdObjectiveIdRoute =
  PracticeSubjectIdObjectiveIdRouteImport.update({
    id: '/practice/$subjectId/$objectiveId',
    path: '/practice/$subjectId/$objectiveId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/flashcards': typeof FlashcardsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/past-papers': typeof PastPapersRoute
  '/quizzes': typeof QuizzesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/subjects': typeof SubjectsRoute
  '/topic': typeof TopicRoute
  '/subject-notes/$subject': typeof SubjectNotesSubjectRoute
  '/syllabus/$subjectId': typeof SyllabusSubjectIdRoute
  '/practice/$subjectId/$objectiveId': typeof PracticeSubjectIdObjectiveIdRoute
  '/topic-notes/$subjectId/$objectiveId': typeof TopicNotesSubjectIdObjectiveIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/flashcards': typeof FlashcardsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/past-papers': typeof PastPapersRoute
  '/quizzes': typeof QuizzesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/subjects': typeof SubjectsRoute
  '/topic': typeof TopicRoute
  '/subject-notes/$subject': typeof SubjectNotesSubjectRoute
  '/syllabus/$subjectId': typeof SyllabusSubjectIdRoute
  '/practice/$subjectId/$objectiveId': typeof PracticeSubjectIdObjectiveIdRoute
  '/topic-notes/$subjectId/$objectiveId': typeof TopicNotesSubjectIdObjectiveIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/flashcards': typeof FlashcardsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/past-papers': typeof PastPapersRoute
  '/quizzes': typeof QuizzesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/subjects': typeof SubjectsRoute
  '/topic': typeof TopicRoute
  '/subject-notes/$subject': typeof SubjectNotesSubjectRoute
  '/syllabus/$subjectId': typeof SyllabusSubjectIdRoute
  '/practice/$subjectId/$objectiveId': typeof PracticeSubjectIdObjectiveIdRoute
  '/topic-notes/$subjectId/$objectiveId': typeof TopicNotesSubjectIdObjectiveIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/flashcards'
    | '/home'
    | '/login'
    | '/notes'
    | '/onboarding'
    | '/past-papers'
    | '/quizzes'
    | '/search'
    | '/settings'
    | '/subjects'
    | '/topic'
    | '/subject-notes/$subject'
    | '/syllabus/$subjectId'
    | '/practice/$subjectId/$objectiveId'
    | '/topic-notes/$subjectId/$objectiveId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/flashcards'
    | '/home'
    | '/login'
    | '/notes'
    | '/onboarding'
    | '/past-papers'
    | '/quizzes'
    | '/search'
    | '/settings'
    | '/subjects'
    | '/topic'
    | '/subject-notes/$subject'
    | '/syllabus/$subjectId'
    | '/practice/$subjectId/$objectiveId'
    | '/topic-notes/$subjectId/$objectiveId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/flashcards'
    | '/home'
    | '/login'
    | '/notes'
    | '/onboarding'
    | '/past-papers'
    | '/quizzes'
    | '/search'
    | '/settings'
    | '/subjects'
    | '/topic'
    | '/subject-notes/$subject'
    | '/syllabus/$subjectId'
    | '/practice/$subjectId/$objectiveId'
    | '/topic-notes/$subjectId/$objectiveId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FlashcardsRoute: typeof FlashcardsRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  OnboardingRoute: typeof OnboardingRoute
  PastPapersRoute: typeof PastPapersRoute
  QuizzesRoute: typeof QuizzesRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SubjectsRoute: typeof SubjectsRoute
  TopicRoute: typeof TopicRoute
  SubjectNotesSubjectRoute: typeof SubjectNotesSubjectRoute
  SyllabusSubjectIdRoute: typeof SyllabusSubjectIdRoute
  PracticeSubjectIdObjectiveIdRoute: typeof PracticeSubjectIdObjectiveIdRoute
  TopicNotesSubjectIdObjectiveIdRoute: typeof TopicNotesSubjectIdObjectiveIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topic': {
      id: '/topic'
      path: '/topic'
      fullPath: '/topic'
      preLoaderRoute: typeof TopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past-papers': {
      id: '/past-papers'
      path: '/past-papers'
      fullPath: '/past-papers'
      preLoaderRoute: typeof PastPapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syllabus/$subjectId': {
      id: '/syllabus/$subjectId'
      path: '/syllabus/$subjectId'
      fullPath: '/syllabus/$subjectId'
      preLoaderRoute: typeof SyllabusSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject-notes/$subject': {
      id: '/subject-notes/$subject'
      path: '/subject-notes/$subject'
      fullPath: '/subject-notes/$subject'
      preLoaderRoute: typeof SubjectNotesSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic-notes/$subjectId/$objectiveId': {
      id: '/topic-notes/$subjectId/$objectiveId'
      path: '/topic-notes/$subjectId/$objectiveId'
      fullPath: '/topic-notes/$subjectId/$objectiveId'
      preLoaderRoute: typeof TopicNotesSubjectIdObjectiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$subjectId/$objectiveId': {
      id: '/practice/$subjectId/$objectiveId'
      path: '/practice/$subjectId/$objectiveId'
      fullPath: '/practice/$subjectId/$objectiveId'
      preLoaderRoute: typeof PracticeSubjectIdObjectiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FlashcardsRoute: FlashcardsRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  OnboardingRoute: OnboardingRoute,
  PastPapersRoute: PastPapersRoute,
  QuizzesRoute: QuizzesRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SubjectsRoute: SubjectsRoute,
  TopicRoute: TopicRoute,
  SubjectNotesSubjectRoute: SubjectNotesSubjectRoute,
  SyllabusSubjectIdRoute: SyllabusSubjectIdRoute,
  PracticeSubjectIdObjectiveIdRoute: PracticeSubjectIdObjectiveIdRoute,
  TopicNotesSubjectIdObjectiveIdRoute: TopicNotesSubjectIdObjectiveIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
