# Generated by Django 6.0.3 on 2026-03-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_study_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
