# Generated by Django 6.0.3 on 2026-04-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_status',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
