# Generated by Django 6.0.3 on 2026-04-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='FlowState', max_length=100)),
                ('tutorial_video_url', models.URLField(blank=True, help_text='YouTube/Vimeo embed URL (e.g. https://www.youtube.com/embed/XXXX)')),
                ('tutorial_video_file', models.FileField(blank=True, help_text='Upload a local MP4 video file', null=True, upload_to='system/videos/')),
                ('is_tutorial_enabled', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Configuration',
                'verbose_name_plural': 'Global Configuration',
            },
        ),
    ]
